export const trendingMockData = [
	{
		profileUrl: "https://dadamda-board-thumbnail.s3.ap-northeast-2.amazonaws.com/profileImage/a45339b0-6d80-4013-954d-f9cb18dda6a6",
		nickname: "즐거운판다5840",
		description:
			"텐동 - 네코정\n사케동 - 아소코, 일상다반\n돈카츠 - 백소정, 휴돈정\n대창덮밥 - 로지다이닝\n카레 - 솔직하다",
		title: "공릉 맛집 정리 - 일식편",
		tag: "ENTERTAINMENT_ART",
		heartCnt: 0,
		shareCnt: 0,
		viewCnt: 0,
		createdAt: 1699069078,
		thumbnailUrl: "",
		uuid: "f542acb3-db2c-4b6a-be5b-1edf0945575e",
		contents: {
			H: [
				{
					scrapId: 825,
					description:
						"내용에 따라 자동으로 북마크를 구성하는 신개념 컨텐츠 맞춤 스크랩 서비스, 다담다",
					pageUrl: "https://dadamda.me/main",
					siteName: null,
					thumbnailUrl:
						"https://dadamda.me/dadamda_img.png",
					title: "세상의 모든 URL, 다담다",
					memoList: [
						{
							memoId: 826,
							memoText: null,
							memoImageUrl:
								"https://dadamda.me/assets/section3Image1-9e37b214.png",
							createdDate: 1698749214,
						},
						{
							memoId: 827,
							memoText: "크롬익스텐션을 설치하시면 이미지 메모도 추가 가능합니다!",
							memoImageUrl: null,
							createdDate: 1698749267,
						},
					],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "825.9942808221645",
				},
			],
			A: [
				{
					scrapId: 838,
					description:
						"서로의 진짜 일상을 공유하는 SNS",
					pageUrl: "https://play.google.com/store/apps/details?id=com.sleepy.mollu",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/D0Gw-IORvs8-qeEPzvjjG90As2maRPzLfgIJkuZ1fVCBsQG5sH34uoBB0fcC0nXbcNMG=w600-h300-pc0xffffff-pd",
					title: "MOLLU - 몰루 - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "838.2895220011808",
				},
				{
					scrapId: 839,
					description: null,
					pageUrl: "https://devridge.dev/",
					siteName: null,
					thumbnailUrl: null,
					title: "DEVRIDGE - 개발자 취업 중심 로드맵 서비스",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "839.8520622907905",
				},
				{
					scrapId: 840,
					description:
						"[EVENT] 지금 다운로드 후 챌린지 참여하면 상품 100% 지급해드려요.",
					pageUrl: "https://play.google.com/store/apps/details?id=com.sav_able.kr&hl=ko-KR",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/M8xAU8vQ31MlnrGI_WiGvEtOFhamATjNE0k6EkJqD_xSwBybvr6PZbORM8FWFP4cfFo=w600-h300-pc0xffffff-pd",
					title: "세이버블 - 기프티콘 100% 지급 이벤트 진행중 - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "840.5079865937236",
				},
				{
					scrapId: 841,
					description:
						"PC에서도 할 수 있는 AI 자동 음성 기록 서비스. 받아 쓰기는 최신 AI 기술에게 맡기고 회의나 강의에 집중하세요.",
					pageUrl: "https://landing.synnote.com/",
					siteName: null,
					thumbnailUrl:
						"https://framerusercontent.com/images/NDyNAvrsitc3pslErx4qDClA1Y.png",
					title: "Synnote - 자동 음성 기록 서비스",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "841.8954977826827",
				},
				{
					scrapId: 837,
					description:
						"‎러닝잇과 함께 기술면접 인터뷰를 준비해보세요!\n\n[문제 리스트 & 풀이]\n- 면접에서 나올만한 필수적인 CS 문제들을 엄선했어요.\n- 빈칸에 핵심 키워드를 채워넣으며 학습해보세요.\n\n[AI 질문 & 답변]\n- 문제에 대해 궁금한점을 질문하고 답변받을 수 있어요.\n\n[추천 문제]\n- 매일마다 새롭게 CS 문제를 추천해줘요.\n\n[찜하기 & 검색]\n- 마음에 드는 문제를 찜해서 모아보고, 검색을 통해 빠르게 찾을 수 있어요.",
					pageUrl: "https://apps.apple.com/kr/app/%EB%9F%AC%EB%8B%9D%EC%9E%87-%EA%B8%B0%EC%88%A0-%EB%A9%B4%EC%A0%91-%EB%8C%80%EB%B9%84-cs-%ED%95%99%EC%8A%B5/id6451151076",
					siteName: null,
					thumbnailUrl:
						"https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/26/b0/26/26b0269f-9b24-6eaa-70b8-6233ea6c0738/AppIcon-1x_U007emarketing-0-6-0-85-220.png/1200x600wa.png",
					title: "‎러닝잇 - 기술 면접 대비 CS 학습",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "837.7507209986105",
				},
				{
					memoId: 1698749174,
					memoText: "안녕하세요! '다담다' 서비스를 개발한 영원한 팀입니다!\n소프트웨어 마에스트로 14기 프로젝트들을 모아보았습니다.\n혹시, 본인의 프로젝트의 추가나 삭제, 편집을 원하시면 이메일로 알려주세요!\n(dadamda.corporation@gmail.com)",
					createdDate: 1698749174,
					id: "1698749174.0144875",
				},
				{
					memoId: 1698749528,
					memoText: "해당 링크는 저희 서비스를 홍보하는 데에 사용될 예정입니다. 혹시 원하지 않는다면 위 이메일로 알려주세요.",
					createdDate: 1698749528,
					id: "1698749528.8016436",
				},
				{
					memoId: 1698749352,
					memoText: "원하는 서비스를 클릭하시면 바로 해당 링크로 이동할 수 있습니다!",
					createdDate: 1698749352,
					id: "1698749352.980903",
				},
			],
			D: [
				{
					scrapId: 806,
					description:
						"AI를 통해 얼굴형을 분석받고, 자연스럽게 헤어스타일을 바꿔보세요",
					pageUrl: "https://play.google.com/store/apps/details?id=com.atowner.hairbe&hl=ko-KR",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/hyI8C55NMg-Sz-LaLcko8JwGc2DgW-_RnOQuTHHWtHgwodhbJl_qZ9r-J-LXV7FjEQ=w600-h300-pc0xffffff-pd",
					title: "헤어비 : 얼굴형 분석과 가상헤어 체험 - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "806.1804888713399",
				},
				{
					scrapId: 799,
					description:
						"세상에 없던 아이디에이션 서포팅 서비스",
					pageUrl: "https://thinkwithme.io",
					siteName: null,
					thumbnailUrl:
						"https://thinkwithme.io/images/preview.png",
					title: "Think with Me",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "799.1429444340006",
				},
				{
					scrapId: 813,
					description: "수공예품 거래 플랫폼",
					pageUrl: "https://play.google.com/store/apps/details?id=com.palindrome.leporemart&hl=ko-KR",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/TiV7gmIBdHe9drs8HGIP3KG-iboYre29KY4cIesXU-2xLItyXB6JXkIjrj_gLYOquA=w600-h300-pc0xffffff-pd",
					title: "공예쁨 - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "813.4923012140754",
				},
				{
					scrapId: 797,
					description:
						"나만을 위한 유튜브 강의 관리 플랫폼 스룸",
					pageUrl: "https://sroom.kr",
					siteName: null,
					thumbnailUrl:
						"https://sroom.kr/image/opengraph/opengraph-image.jpg",
					title: "스룸",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "797.9376072610073",
				},
			],
			E: [
				{
					scrapId: 794,
					description:
						"일기 쓰기, 매번 작심삼일에 그쳤다면? 하루에 30초만 짧게 남기고, AI 친구 Moo에게 일기 작성을 맡겨보세요!",
					pageUrl: "https://play.google.com/store/apps/details?id=com.moodmemo&hl=ko-KR",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/dGTlba_tgG2GeAm45fwWNG8JyLfOqhyqF26E2d1hMGByWHwx6iG1BPVT6pRUul1jOg=w600-h300-pc0xffffff-pd",
					title: "무드메모 - AI일기, 일기, 감정일기, 다이어리 - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "794.576627218374",
				},
				{
					scrapId: 817,
					description:
						"도서로 사람과 사람을 연결하고, 도서의 가치를 발견하다.",
					pageUrl: "https://play.google.com/store/apps/details?id=kr.mybrary.mybrary&hl=ko-KR",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/mRTkeVbqxReqJM8sOBQ7m5x5yekomztStvNcy0QJHDr_vNZPUFZXsecef0-2LX2fig=w600-h300-pc0xffffff-pd",
					title: "마이브러리 - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "817.4687214708762",
				},
				{
					scrapId: 807,
					description:
						"실력있는 현업 개발자를 나만의 코딩 멘토로! 코드리뷰로 부업하고 싶은 실력있는 개발자도 컴온~!",
					pageUrl: "https://play.google.com/store/apps/details?id=com.lgtm.android&hl=ko-KR",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/5BMZktZE3ds2c9_RINern0Pon-RLILLsn1ZjTgJvx_t19kZ9DmFfpe8ioO-Dsk9hDIA=w600-h300-pc0xffffff-pd",
					title: "LGTM - 코드리뷰 매칭 플랫폼 - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "807.4017826859902",
				},
				{
					scrapId: 816,
					description:
						"중고 맥 가격 비교는 MacGuider",
					pageUrl: "https://www.macguider.io",
					siteName: null,
					thumbnailUrl:
						"https://macguider.io/static/images/twitter-card.png",
					title: "맥가이더 MacGuider",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "816.9339203443327",
				},
			],
			F: [
				{
					scrapId: 808,
					description:
						"우리 아이가 주인공으로 등장하는 동화를 만들어보세요!",
					pageUrl: "https://play.google.com/store/apps/details?id=com.filo.crepas&hl=ko-KR",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/8UFVxeQvPBfHtY7B89lje48quiN0qlrfuFuvjodbA8t9SLDRLcD2gNblM-SVHWWziI8=w600-h300-pc0xffffff-pd",
					title: "꼬북 - 우리 아이가 주인공인 동화 - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "808.6184772907145",
				},
				{
					scrapId: 811,
					description:
						"함께 더 즐겁게, 실시간 대결 러닝 서비스 플랫폼",
					pageUrl: "https://play.google.com/store/apps/details?id=online.partyrun.partyrunapplication&hl=ko-KR",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/M1-tHeGoQ-_sEZBcgj6MKqoMMNdDRnEVglq4bL4FOxky9ffPloVuuskM8szaDFF90g=w600-h300-pc0xffffff-pd",
					title: "파티런 - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "811.4678750972384",
				},
				{
					scrapId: 822,
					description:
						"모두의 랜덤 디펜스: 코딩테스트를 준비하는 최고의 솔루션!",
					pageUrl: "https://morandi.co.kr",
					siteName: null,
					thumbnailUrl: null,
					title: "모두의 랜덤 디펜스",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "822.4463023176639",
				},
				{
					scrapId: 798,
					description: "퀴즈잇(Quizit)",
					pageUrl: "https://quizit.org/auth/login",
					siteName: null,
					thumbnailUrl:
						"https://quizit.org/icons/android/drawable-xxxhdpi/icon",
					title: "퀴즈잇(Quizit)",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "798.0244922423099",
				},
			],
			G: [
				{
					scrapId: 823,
					description:
						"근무표, 이제 더 간편하게!",
					pageUrl: "https://www.dutying.net",
					siteName: null,
					thumbnailUrl:
						"https://www.dutying.net/img/og-image.png",
					title: "듀팅",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "823.5661272154173",
				},
				{
					scrapId: 812,
					description:
						"알아서 잘 딱 깔끔하게 센스있게, 기특한 기프티콘 관리 서비스",
					pageUrl: "https://play.google.com/store/apps/details?id=org.swmaestro.repl.GiftHub&hl=ko-KR",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/dV9m1tdEKV3bM8b6HbUJIKbQkDhqkdK7skL_WLVx1kxQ-62Whcf-bfaZdiG_6nMsEg=w600-h300-pc0xffffff-pd",
					title: "GiftHub - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "812.5301906222595",
				},
				{
					scrapId: 809,
					description:
						"소중한 날을 더 소중하게 즐겁고 간편한 케이크 주문",
					pageUrl: "https://play.google.com/store/apps/details?id=com.klh.kezzle&hl=ko-KR",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/L3Vx37CqfYETG_fnIpXavzMk6nsfizIQ7OlLyG0E48xHEV_8ZNTROzIlNKKAxJKu6S8=w600-h300-pc0xffffff-pd",
					title: "Kezzle - 간편한 레터링 케이크 주문 앱, 케즐 - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "809.5469026060077",
				},
			],
			B: [
				{
					scrapId: 801,
					description: null,
					pageUrl: "https://www.inforum.me",
					siteName: null,
					thumbnailUrl:
						"https://www.inforum.me/_next/static/media/metadata/opengraph-image.00febf01.jpeg",
					title: "인포럼 - 무한한 개발 이야기 공간",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "801.3458641124604",
				},
				{
					scrapId: 795,
					description:
						"AI 기반 영어 스피킹 연습부터 외국인 친구와의 실전 경험까지, 모두 블라블라에서!",
					pageUrl: "https://play.google.com/store/apps/details?id=net.blablah.blabla&hl=ko-KR",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/e2z3uhqQnE433a30KdojDIm5lqveIv8JnTVZI8IC0aRqUdUQ2vFCSJVMucYoStxAXRA=w600-h300-pc0xffffff-pd",
					title: "블라블라(blabla) - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "795.1862501313914",
				},
				{
					scrapId: 810,
					description:
						"레시피에이드는 요리하는 순간의 경험을 향상시키는 서비스로, 요리 영상을 쉽게 찾아보고 더욱 편리하게 요리할 수 있습니다.",
					pageUrl: "https://play.google.com/store/apps/details?id=com.recipeade.svelte&hl=ko-KR",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/1I5JKeN6-50-CoMyIc7QXqlRdQX4oTu6S-L1ZbxM78AUC7sdyeCfdp5xwUcggVckTw=w600-h300-pc0xffffff-pd",
					title: "레시피에이드 - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "810.0753596500622",
				},
				{
					scrapId: 814,
					description: null,
					pageUrl: "https://finote.co.kr",
					siteName: null,
					thumbnailUrl: null,
					title: "FiNote",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "814.0260762493918",
				},
			],
			C: [
				{
					scrapId: 804,
					description:
						'"소개팅 어플은 많은데, 대학생 미팅은 어디서 구하지? 매일 밤 11시 11분, 위밋에서 네게 딱 맞는 친구들을 만나봐"',
					pageUrl: "https://play.google.com/store/apps/details?id=net.andrewjsy.wemeet",
					siteName: null,
					thumbnailUrl:
						"https://play-lh.googleusercontent.com/GwnYCoZI6gfdaEtPwZqvMhPoAHQcZcF_qHeyzjm8VZTVZyPXsw5WK9vwR8UnrYJrzA=w600-h300-pc0xffffff-pd",
					title: "위밋 - 대학생 미팅/과팅 여기서 만나 - Google Play 앱",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "804.4407716877291",
				},
				{
					scrapId: 805,
					description:
						"클릭 한 번으로 자동화하는 사내 프로세스, 업무에 필요한 반복적인 작업을 자동화하고 동료에게 놀라운 경험을 선사하세요.",
					pageUrl: "https://www.workplug.team",
					siteName: null,
					thumbnailUrl:
						"https://framerusercontent.com/images/KnWDZ3uBw9jd9i0r33LYU8b00ew.png",
					title: "워크플러그 - 사내 프로세스 자동화 SaaS",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "805.8176301936594",
				},
				{
					scrapId: 819,
					description: null,
					pageUrl: "https://jikting.com",
					siteName: null,
					thumbnailUrl: null,
					title: "직팅",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "819.0602494678627",
				},
				{
					scrapId: 796,
					description: null,
					pageUrl: "https://moview.io",
					siteName: null,
					thumbnailUrl: null,
					title: "모두의 인터뷰",
					memoList: [],
					author: null,
					authorImageUrl: null,
					blogName: null,
					publishedDate: null,
					price: null,
					channelImageUrl: null,
					channelName: null,
					embedUrl: null,
					playTime: null,
					watchedCnt: null,
					dtype: "other",
					id: "796.7837730323374",
				},
			],
		},
	},
	{
		profileUrl: "https://dadamda-board-thumbnail.s3.ap-northeast-2.amazonaws.com/profileImage/a45339b0-6d80-4013-954d-f9cb18dda6a6",
		nickname: "즐거운판다5840",
		description:
			"텐동 - 네코정\n사케동 - 아소코, 일상다반\n돈카츠 - 백소정, 휴돈정\n대창덮밥 - 로지다이닝\n카레 - 솔직하다",
		title: "공릉 맛집 정리 - 일식편",
		tag: "ENTERTAINMENT_ART",
		heartCnt: 0,
		shareCnt: 0,
		viewCnt: 0,
		createdAt: 1699069078,
		thumbnailUrl: "",
		uuid: "f542acb3-db2c-4b6a-be5b-1edf0945575e",
		contents: {},
	},
];
